site_name: Лабораторная работа 3 - Docker и Celery интеграция
site_description: Документация по созданию Dockerfile, Docker Compose и интеграции Celery с Redis
site_author: Студент
site_url: https://example.com

# Настройки темы
theme:
  name: material
  language: ru
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Переключить на темную тему
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - search.highlight
    - search.share
    - content.code.copy

# Настройки плагинов
plugins:
  - search

# Настройки markdown
markdown_extensions:
  - codehilite:
      guess_lang: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Структура навигации
nav:
  - Главная: index.md
  - Задача 1 - Dockerfile:
    - Создание Dockerfile: dockerfile/creation.md
    - Конфигурация: dockerfile/configuration.md
    - Примеры: dockerfile/examples.md
  - Задача 2 - Docker Compose:
    - Создание docker-compose.yml: docker-compose/creation.md
    - Управление сервисами: docker-compose/services.md
    - Конфигурация: docker-compose/configuration.md
  - Задача 3 - FastAPI и парсер:
    - Создание эндпоинтов: fastapi/endpoints.md
    - Интеграция парсера: fastapi/parser-integration.md
    - Примеры API: fastapi/examples.md
  - Задача 4 - Celery и Redis:
    - Настройка Celery: celery/setup.md
    - Настройка Redis: redis/setup.md
    - Асинхронные задачи: celery/tasks.md
    - Интеграция с FastAPI: celery/fastapi-integration.md

# Дополнительные настройки
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com
  version:
    provider: mike